### ISSUE TITLE
General thoughts

### ISSUE THREAD

**Issue by hazbo** [jamiefdhurst/go-wardrobe#1]
Hi Jamie, this is great! It's always nice to see new people working with Go and getting into it. I think you've done a pretty great job. I just thought it might be nice to perhaps share a few thoughts with you on this.

So unlike a lot of other languages, the case for things that we name is meaningful in Go. For example, if you're writing a package that has a `User` struct, it may look a bit like this:

```go
package user

type User struct {
    Name string
    Age int
}
```

upon import of that package, not only do we have access to `User`, but each of the fields within in, in this case Name and Age. This is simply because they're exported, and we represent that by making the first character uppercase.

So within func main, you define `const Version = "0.1"`. This is fine and will work, although out of convention if this was not going to be used outside of the package it is defined in, we'd probably just say: `const version = "0.1"`.

The same applies for function names, in other languages you might define a function as `private` for example - if it is only meant to be used internally within its class / package. In Go we'd just define it starting with the lowercase.

When it comes to printing the version, we can concat strings using `+` much like in many other languages. We can print things using the `fmt` package in other ways using formatting, which is also common in other languages. For example,

```go
fmt.Println("Wardrobe v" + Version + "...")
fmt.Println("-------------------")
fmt.Println("")
```

could be represented as:

```go
fmt.Printf("Wardrobe v%s...\n", Version)
fmt.Printf("-------------------\n")
```

or even just

```go
fmt.Printf("Wardrobe v%s...\n-------------------\n", Version)
```

although you may agree that the last way might be a bit messier!

I didn't want to make a pull request for little things like this as I figured it might be more useful to just explain them. I found this because of your tweet by the way. From that I gathered that this was a fairly early piece of work you'd written in Go, and I think you've done a really good job. :)

P.S. Sorry for typos etc... I've had a few beers.

**Comment by jamiefdhurst** [comment]
Harry,

Many many thanks for your comments - I really appreciate that you've gone through and explained things to me.

I think a lot of this is just down to experience - you're right, this is the first publicly released go I've written, so you can imagine some of the stuff behind the scenes is a little bit worse, to say the least...

I think I need to do a little bit more exploring within the standard lib documentation, and then I'll come across fmt.Printf, etc. which would make life a lot easier.

Bear in mind I'm used to writing PHP, where being verbose and commenting all over is kind of the norm,.

I'll take your feedback on board and push through a new commit later today.

Many thanks again! :)
